### PR TITLE
Make sure to get a storage dependent valid file name when handling uploaded files

### PR DESCRIPTION
**Pull request by charettes**
Django doesn't play well with uploaded files containing non-ascii char.

On way to get around this issue is creating a custom storage backend.

``` python
import unicodedata

from django.core.files.storage import FileSystemStorage

class ASCIIFileSystemStorage(FileSystemStorage):
    """Convert unicode characters in name to ASCII characters."""
    def get_valid_name(self, name):
        name = unicodedata.normalize('NFKD', name).encode('ascii', 'ignore')
        return super(ASCIIFileSystemStorage, self).get_valid_name(name)
```

And defining it as the default storage backend in you settings.

``` python
DEFAULT_FILE_STORAGE = 'common.storage.ASCIIFileSystemStorage'
```

However django-form-designer's upload mechanism doesn't honor the storage dependent valid file name scheme. The attached pull request fixes that.

### CODE REVIEW

**Comment by samluescher** [comment]
What file system is this necessary for?

**Comment by charettes** [comment]
I guess you can encounter this issue on multiple file systems but we had issues on a linux box

```
Traceback (most recent call last):

 File ".../lib/django/core/handlers/base.py", line 111, in get_response
   response = callback(request, *callback_args, **callback_kwargs)

 File ".../lib/django/views/generic/simple.py", line 28, in direct_to_template
   return HttpResponse(t.render(c), mimetype=mimetype)

 File ".../lib/django/template/base.py", line 123, in render
   return self._render(context)

 File ".../lib/django/template/base.py", line 117, in _render
   return self.nodelist.render(context)

 File ".../lib/django/template/base.py", line 744, in render
   bits.append(self.render_node(node, context))

 File ".../lib/django/template/debug.py", line 73, in render_node
   result = node.render(context)

 File ".../lib/django/template/loader_tags.py", line 127, in render
   return compiled_parent._render(context)

 File ".../lib/django/template/base.py", line 117, in _render
   return self.nodelist.render(context)

 File ".../lib/django/template/base.py", line 744, in render
   bits.append(self.render_node(node, context))

 File ".../lib/django/template/debug.py", line 73, in render_node
   result = node.render(context)

 File ".../lib/classytags/core.py", line 102, in render
   return self.render_tag(context, **kwargs)

 File ".../lib/sekizai/templatetags/sekizai_tags.py", line 66, in render_tag
   rendered_contents = nodelist.render(context)

 File ".../lib/django/template/base.py", line 744, in render
   bits.append(self.render_node(node, context))

 File ".../lib/django/template/debug.py", line 73, in render_node
   result = node.render(context)

 File ".../lib/classytags/core.py", line 102, in render
   return self.render_tag(context, **kwargs)

 File ".../lib/sekizai/templatetags/sekizai_tags.py", line 66, in render_tag
   rendered_contents = nodelist.render(context)

 File ".../lib/django/template/base.py", line 744, in render
   bits.append(self.render_node(node, context))

 File ".../lib/django/template/debug.py", line 73, in render_node
   result = node.render(context)

 File ".../lib/django/template/loader_tags.py", line 64, in render
   result = block.nodelist.render(context)

 File ".../lib/django/template/base.py", line 744, in render
   bits.append(self.render_node(node, context))

 File ".../lib/django/template/debug.py", line 73, in render_node
   result = node.render(context)

 File ".../lib/django/template/loader_tags.py", line 64, in render
   result = block.nodelist.render(context)

 File ".../lib/django/template/base.py", line 744, in render
   bits.append(self.render_node(node, context))

 File ".../lib/django/template/debug.py", line 73, in render_node
   result = node.render(context)

 File ".../lib/classytags/core.py", line 102, in render
   return self.render_tag(context, **kwargs)

 File ".../lib/cms/templatetags/cms_tags.py", line 220, in render_tag
   content = get_placeholder_content(context, request, page, name, inherit)

 File ".../lib/cms/templatetags/cms_tags.py", line 145, in get_placeholder_content
   content = render_placeholder(placeholder, context, name)

 File ".../lib/cms/plugin_rendering.py", line 127, in render_placeholder
   c.extend(render_plugins(plugins, context, placeholder, processors))

 File ".../lib/cms/plugin_rendering.py", line 81, in render_plugins
   c.append(plugin.render_plugin(context, placeholder, processors=processors))

 File ".../lib/cms/models/pluginmodel.py", line 172, in render_plugin
   context = plugin.render(context, instance, placeholder_slot)

 File ".../lib/form_designer/cms_plugins.py", line 20, in render
   return process_form(context['request'], instance.form_definition, context, is_cms_plugin=True)

 File ".../lib/form_designer/views.py", line 39, in process_form
   files = handle_uploaded_files(form_definition, form)

 File ".../lib/form_designer/uploads.py", line 48, in handle_uploaded_files
   '%s_%s%s' % (root, secret_hash, ext)))

 File ".../lib/django/core/files/storage.py", line 74, in get_available_name
   while self.exists(name):

 File ".../lib/django/core/files/storage.py", line 218, in exists
   return os.path.exists(self.path(name))

 File "/usr/lib/python2.6/genericpath.py", line 18, in exists
   st = os.stat(path)

TemplateSyntaxError: Caught UnicodeEncodeError while rendering: 'ascii' codec can't encode character u'\xc9' in position 82: ordinal not in range(128)
```

But this fix is really more about being more consistent with the way django's `FileField` [handles this](https://github.com/django/django/blob/master/django/db/models/fields/files.py#L259..L263) since we're only encountering this issue using django-form-designer's upload mechanism and all other upload fields work just fine when defining a new file storage.

**Comment by samluescher** [comment]
OK, I see, that's the way it should be. At first I thought you wanted to merge the ASCIIFileSystemStorage itself, but that would have been outside the scope of this app.

**Comment by charettes** [comment]
I agree, thanks for merging!

**Pull request merged**
