### PR TITLE
Polish translation, tiny fix

### PR DESCRIPTION
**Pull request by piotrkilczuk**
Hello, 

Being quite in a hurry, I've translated the .po file to pl locale, as well as corrected one obvious typo in README.md.

Regards, 
Piotr

### CODE REVIEW

**Comment by samluescher** [comment]
Thank you for your work! After abandoning the app for over a year, I finally found the time to pick it up again and merge a huge amount of changes. Your pull request cannot be merged -- would you mind updating to the current master and re-submitting your translation?

**Comment by piotrkilczuk** [comment]
I guess the problem is with c15c13c?

**Comment by samluescher** [comment]
That's right, the other commit should work without problems.

**Comment by piotrkilczuk** [comment]
Could you please just cherry-pick the first commit? I'm not able, due to deadlines, to tide up my fork at the moment. The readme correction is not that important IMO....

Thanks

**Pull request closed without merging**
